backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "photos"
    label: "照片"
    folder: "src/content/photos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "標題", name: "title", widget: "string"}
      - {label: "日期", name: "date", widget: "datetime"}
      - {label: "圖片", name: "image", widget: "image"}
      - {label: "描述", name: "body", widget: "markdown"}
